version: '3.5'

services:
    webserver:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - elastic-network
        depends_on:
            - elasticsearch
    php:
        image: php:7-fpm
        volumes:
            - ./code:/code
        networks:
            - elastic-network
        depends_on:
            - elasticsearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
        container_name: elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"
        volumes:
            - elasticsearch-vol:/usr/share/elasticsearch/data 
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - elastic-network
    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.2
        ports:
            - "5601:5601"
        networks:
            - elastic-network
        depends_on:
            - elasticsearch

volumes:
  elasticsearch-vol: 

networks:
  elastic-network:
    name: elastic-network